### PR TITLE
Make Handler accept a Parameter. Fixes #23

### LINKED ISSUE #23: Handler should decide whether it is Binary<Parameter, Block> or Binary<Var, Block>
Currently it is Handler<Decl,Block>.
With the current C++, the only things that can fit the Decl is either a Parameter or Var. 
Unless there is some evolution path where C++ may acquire other kinds of catch clauses, we should narrow the IPR for Handler to either have a Parameter or a Var as a first operand.

### PR DESCRIPTION
**Pull request by Xazax-hun**

### CODE REVIEW

**Comment by GabrielDosReis** [comment]
The discussion in #23 suggests two alternatives: either a variable or a parameter.  Any rationale for what tipped the choice toward parameter instead of variable?

**Comment by Xazax-hun** [comment]
You mentioned in #23 that `Handler` is a functional abstraction and that makes it closer to a `Parameter` rather than a `Var`. I followed that advice. I agree with you, the initialization of a handler parameter is conceptually similar to how argument passing works. But I don't have a strong preference either way. For reference: it is `VarDecl` in clang. I did not find anything in the C++ standard that would mandate one over the other.

**Comment by GabrielDosReis** [comment]
Correct, and that is why I am trying to suss out what tipped the balance so that we record that in the definition of the `Handler`.

The reason why I see EH object as more of `Parameter` is because of their initialization semantics.  On the other hand, you can also make the argument that a parameter is a local variable.

IPR is focusing on getting to the essence of C++ -- and not try to mimic or copy one particular compiler data structure.

Given the ambiguity, I suspect introducing a distinct node `EH_var` might be a better resolution -- very much similar to `Parameter`.

**Comment by Xazax-hun** [comment]
I think I don't like the idea of `EH_var`, as this information can be easily reverse-engineered from the context. I.e.: we could easily add a helper function like `is_eh_var/is_eh_param` in a separate module that could look at the parent (in case we can do that relatively easily/cheaply).  But my assumptions might be wrong, as I just started to look into the code base :)

**Comment by GabrielDosReis** [comment]
Hmm, the question is how often does one need to do when one sees a `Parameter`, e.g. how often does one need to remember to check for that predicate?

**Comment by GabrielDosReis** [comment]
I am a working on a more extensive fix

**Pull request closed without merging**
