### PR TITLE
Add result types to expr_factory. Fixes #1.

### LINKED ISSUE #1: Add variants of expression factory function to ipr::impl::Unit::make_xxx() to take result type
Expression node factory functions such as `ipr::impl::Unit::make_plus()` don't currently take the type of the expression as argument.  It would be nice to have that convenience.

### PR DESCRIPTION
**Pull request by Xazax-hun**
Let me know if you want both overloads (with and without result type). If that is the case, I will extend this PR.

### CODE REVIEW

**Comment by GabrielDosReis** [comment]
Suggestion #1 is for convenience, not fundamental.  An implementation that doubles the interface surface would be wild.  The issue here is that the result type is optional, in the sense that it may not be present for example in templated code where the operands are dependent.  So the absence of the return type is a necessity.  Because the factory functions return a pointer to the `impl` type, it is always possible to the result type when available.  So the suggestion #1 calls for an optional result type in the factory function.  So they would take for example an additional `Optional<ipr::Type>` parameter that defaults to `{ }` (i.e. nothing).

**Comment by Xazax-hun** [comment]
Do we prefer optional reference to pointers?

**Comment by GabrielDosReis** [comment]
Yes, prefer `Optional<T>` over `T*` when the intent is to indicate optionality.  Use `T&` to indicate requirement.

**Comment by Xazax-hun** [comment]
> Yes, prefer Optional<T> over T* when the intent is to indicate optionality. Use T& to indicate requirement.
Thanks, after #93 this is much clearer.

I updated this PR to take the result type as Optional.

**Pull request merged**
